spring:
  datasource:
    url: jdbc:h2:C:/Users/these/Desktop/db/space/module17
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    user:
      name: user
      password: default